<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_loginusername</name>
   <tag></tag>
   <elementGuidId>4ebcd552-d532-4a42-b8de-c89ba04d70c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginusername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginusername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1b8bf37-8542-443c-b4ac-8629b2d1e01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd7ffe00-e8ef-41b3-b8c2-9bca05135220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>21656a96-f606-4d5f-875e-926abaf5e792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginusername</value>
      <webElementGuid>34ead662-5304-425b-a60b-77c01a928438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginusername&quot;)</value>
      <webElementGuid>37e52fd7-1ddc-45f9-8226-cf4aa73a5511</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginusername']</value>
      <webElementGuid>e1582db9-ee2a-4f7c-9e9d-1d91ab63f155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logInModal']/div/div/div[2]/form/div/input</value>
      <webElementGuid>31cc072d-0d25-4cc9-85ab-03c7fe48e696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/form/div/input</value>
      <webElementGuid>3e05230b-8851-4e03-9d2a-3848793df7c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'loginusername']</value>
      <webElementGuid>3395a78f-7446-4cba-91f6-d148305bc2af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
